# password_manager configuration

server notls {
	bind 127.0.0.1 8888
	tls no
}

load		./password_manager.so

domain localhost {
	attach		notls

	# Consulter tous les mots de passe
	route /api/passwords {
		handler password_list
        methods get
	}

	# Générer et sauvegarder un nouveau mot de passe
	route /api/passwords/generate {
        handler password_generate
        methods post
    }

	route /api/passwords/delete {
        handler password_delete
        methods delete
    }
}
